### ISSUE TITLE
An issue using `len(vs.evaluation_mask)`

### ISSUE THREAD

**Issue by ZhelunChen** [HichamJohra/energy_flexibility_kpis#27]
https://github.com/HichamJohra/energy_flexibility_kpis/blob/3c539bcfcebaa1bd335fbac08186f198223bad8a/energy_flexibility_kpis/kpi/energy_flexibility/energy_or_average_power_load_shedding.py#L142

@kingsleynweye 
`len(vs.evaluation_mask)` returns the length of the whole time array instead of the evaluation period, but it seems you just want the evaluation period in the equation. Similar issues have been seen in other functions.

**Comment by kingsleynweye** [comment]
@ZhelunChen yeah the way it is written is what is intended i.e., to get the length of the evaluation period. In the example you referenced, I am calculating the average power difference during evaluation period:

```python
value = (
            vs.baseline_electric_power_profile.value[vs.evaluation_mask] 
                - vs.flexible_electric_power_profile.value[vs.evaluation_mask]
        ).sum()/len(vs.evaluation_mask)
```

**Comment by ZhelunChen** [comment]
@kingsleynweye If I have a 24-hour data (24 rows), and I only want to evaluate 3 hours (3 rows), `len(vs.evaluation_mask)` would give me 24 instead of 3.

**Comment by kingsleynweye** [comment]
@ZhelunChen you are right and thanks for catching it. I have fixed the bug in the above linked merge.

**Comment by ZhelunChen** [comment]
Thank you @kingsleynweye
