### ISSUE TITLE
unable to call any kpi function due to this bug

### ISSUE THREAD

**Issue by ZhelunChen** [HichamJohra/energy_flexibility_kpis#30]
https://github.com/HichamJohra/energy_flexibility_kpis/blob/307844ca144a00f8a3498e08d739b42bfb770b9d/energy_flexibility_kpis/variable.py#L446

Getting this error: 
TypeError: __init__() missing 2 required positional arguments: 'primitive_type' and 'value_type'

**Comment by kingsleynweye** [comment]
@ZhelunChen  thanks for catching this. It's been fixed now.
