### ISSUE TITLE
Define environment variables for running pypi_update.yml workflow

### ISSUE THREAD

**Issue by kingsleynweye** [HichamJohra/energy_flexibility_kpis#8]
In the Settings -> Environments -> New environment, create an environment named `pypi` and create 2 environment secrets named:
1. `PYPI_USERNAME`
2. `PYPI_PASSWORD`

The values for these secrets are your PyPi credentials that will be used to automatically publish new releases using #2.

**Comment by HichamJohra** [comment]
ok
